// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ActionPoint string

const (
	ActionPoint_AT_DEPLOYMENT_TICK                      ActionPoint = "AT_DEPLOYMENT_TICK"
	ActionPoint_ON_DEPLOYMENT_BAKING                    ActionPoint = "ON_DEPLOYMENT_BAKING"
	ActionPoint_ON_DEPLOYMENT_COMPLETE                  ActionPoint = "ON_DEPLOYMENT_COMPLETE"
	ActionPoint_ON_DEPLOYMENT_ROLLED_BACK               ActionPoint = "ON_DEPLOYMENT_ROLLED_BACK"
	ActionPoint_ON_DEPLOYMENT_START                     ActionPoint = "ON_DEPLOYMENT_START"
	ActionPoint_ON_DEPLOYMENT_STEP                      ActionPoint = "ON_DEPLOYMENT_STEP"
	ActionPoint_PRE_CREATE_HOSTED_CONFIGURATION_VERSION ActionPoint = "PRE_CREATE_HOSTED_CONFIGURATION_VERSION"
	ActionPoint_PRE_START_DEPLOYMENT                    ActionPoint = "PRE_START_DEPLOYMENT"
)

type BadRequestReason string

const (
	BadRequestReason_InvalidConfiguration BadRequestReason = "InvalidConfiguration"
)

type BytesMeasure string

const (
	BytesMeasure_KILOBYTES BytesMeasure = "KILOBYTES"
)

type DeleteType string

const (
	DeleteType_ARCHIVE DeleteType = "ARCHIVE"
	DeleteType_DESTROY DeleteType = "DESTROY"
)

type DeletionProtectionCheck string

const (
	DeletionProtectionCheck_ACCOUNT_DEFAULT DeletionProtectionCheck = "ACCOUNT_DEFAULT"
	DeletionProtectionCheck_APPLY           DeletionProtectionCheck = "APPLY"
	DeletionProtectionCheck_BYPASS          DeletionProtectionCheck = "BYPASS"
)

type DeploymentEventType string

const (
	DeploymentEventType_BAKE_TIME_STARTED    DeploymentEventType = "BAKE_TIME_STARTED"
	DeploymentEventType_DEPLOYMENT_COMPLETED DeploymentEventType = "DEPLOYMENT_COMPLETED"
	DeploymentEventType_DEPLOYMENT_STARTED   DeploymentEventType = "DEPLOYMENT_STARTED"
	DeploymentEventType_PERCENTAGE_UPDATED   DeploymentEventType = "PERCENTAGE_UPDATED"
	DeploymentEventType_REVERT_COMPLETED     DeploymentEventType = "REVERT_COMPLETED"
	DeploymentEventType_ROLLBACK_COMPLETED   DeploymentEventType = "ROLLBACK_COMPLETED"
	DeploymentEventType_ROLLBACK_STARTED     DeploymentEventType = "ROLLBACK_STARTED"
)

type DeploymentState string

const (
	DeploymentState_BAKING       DeploymentState = "BAKING"
	DeploymentState_COMPLETE     DeploymentState = "COMPLETE"
	DeploymentState_DEPLOYING    DeploymentState = "DEPLOYING"
	DeploymentState_REVERTED     DeploymentState = "REVERTED"
	DeploymentState_ROLLED_BACK  DeploymentState = "ROLLED_BACK"
	DeploymentState_ROLLING_BACK DeploymentState = "ROLLING_BACK"
	DeploymentState_VALIDATING   DeploymentState = "VALIDATING"
)

type DeploymentType string

const (
	DeploymentType_MANAGED DeploymentType = "MANAGED"
	DeploymentType_USER    DeploymentType = "USER"
)

type EnvironmentState string

const (
	EnvironmentState_DEPLOYING            EnvironmentState = "DEPLOYING"
	EnvironmentState_READY_FOR_DEPLOYMENT EnvironmentState = "READY_FOR_DEPLOYMENT"
	EnvironmentState_REVERTED             EnvironmentState = "REVERTED"
	EnvironmentState_ROLLED_BACK          EnvironmentState = "ROLLED_BACK"
	EnvironmentState_ROLLING_BACK         EnvironmentState = "ROLLING_BACK"
)

type ExperimentDefinitionStatus string

const (
	ExperimentDefinitionStatus_ACTIVE   ExperimentDefinitionStatus = "ACTIVE"
	ExperimentDefinitionStatus_ARCHIVED ExperimentDefinitionStatus = "ARCHIVED"
	ExperimentDefinitionStatus_IDLE     ExperimentDefinitionStatus = "IDLE"
)

type ExperimentRunEventType string

const (
	ExperimentRunEventType_EXPOSURE_UPDATED  ExperimentRunEventType = "EXPOSURE_UPDATED"
	ExperimentRunEventType_OVERRIDES_UPDATED ExperimentRunEventType = "OVERRIDES_UPDATED"
	ExperimentRunEventType_RUN_STARTED       ExperimentRunEventType = "RUN_STARTED"
	ExperimentRunEventType_RUN_STOPPED       ExperimentRunEventType = "RUN_STOPPED"
)

type ExperimentRunStatus string

const (
	ExperimentRunStatus_DONE    ExperimentRunStatus = "DONE"
	ExperimentRunStatus_RUNNING ExperimentRunStatus = "RUNNING"
)

type GrowthType string

const (
	GrowthType_EXPONENTIAL GrowthType = "EXPONENTIAL"
	GrowthType_LINEAR      GrowthType = "LINEAR"
)

type ReplicateTo string

const (
	ReplicateTo_NONE         ReplicateTo = "NONE"
	ReplicateTo_SSM_DOCUMENT ReplicateTo = "SSM_DOCUMENT"
)

type TriggeredBy string

const (
	TriggeredBy_APPCONFIG        TriggeredBy = "APPCONFIG"
	TriggeredBy_CLOUDWATCH_ALARM TriggeredBy = "CLOUDWATCH_ALARM"
	TriggeredBy_INTERNAL_ERROR   TriggeredBy = "INTERNAL_ERROR"
	TriggeredBy_USER             TriggeredBy = "USER"
)

type ValidatorType string

const (
	ValidatorType_JSON_SCHEMA ValidatorType = "JSON_SCHEMA"
	ValidatorType_LAMBDA      ValidatorType = "LAMBDA"
)
